# -*- coding: utf-8 -*-
"""Validação Analítica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kVi4HItVzp4S7agthzthJ6RiIV-RpiMc

#Primeiro instalar Streamlit
"""

!pip install streamlit

"""# 1. Escrever o código que deve ser nomeado como app.py
Primeiro, importamos os pacotes necessários. Importar o streamlit como st e também as bibliotecas utilizadas no código.
"""

'''Streamlit app para Validação Analítica'''
import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
import scipy.stats as stats

"""# 2. Introdução sobre o aplicativo"""

#start the app
st.title('Linearidade para Validação Analítica')

st.write('''#### Realização de testes estatísticos para a Validação Analítica de acordo com a RDC 166.

Este é um requisito que deve ser utilizado para métodos desenvolvidos.
''')

"""# 3. Inclusão local para a pessoa colocar os dados"""

import streamlit as st
st.write("#### Input Data")

# Create a DataFrame with the specified columns and 15 rows
data = pd.DataFrame(
    np.zeros((15, 4)),
    columns=['Concentration', 'Response', 'Level', 'Order']
)

# Display the data editor
edited_data = st.data_editor(data, num_rows="dynamic")

# You can access the edited data in the 'edited_data' DataFrame
# For example, to display the edited data:
# st.write("Edited Data:")
# st.write(edited_data)